# Generated by Django 4.0 on 2024-04-06 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editon', models.CharField(max_length=4)),
                ('teams', models.IntegerField()),
                ('matches', models.IntegerField()),
                ('runnerup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='runnerup', to='main.team')),
                ('winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='season_wins', to='main.team')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loser', to='main.team')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mathe', to='main.season')),
                ('team1', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='main.team')),
                ('team2', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='main.team')),
                ('winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='main.team')),
            ],
        ),
    ]
