# Generated by Django 4.0 on 2024-04-09 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_match_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='discription',
            field=models.CharField(default='league-match', max_length=100),
        ),
    ]
