# Generated by Django 4.0 on 2024-04-10 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_match_team1_alter_match_team2'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
